name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  repo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Nix Shell
        run: nix develop -c true -L

      - name: Nix Format
        run: nix develop -c just fmt-check

      - name: Readme Check
        run: nix develop -c just readme-check

  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Nix Shell
        run: nix develop -c true -L

      - name: Build Packages
        run: nix develop -c scripts/build-pkgs.sh
